-- MySQL Script generated by MySQL Workbench
-- Sat Jan 10 12:43:08 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Question` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Question` (
  `ID_Question` INT NOT NULL,
  `Question_Text` VARCHAR(200) NOT NULL,
  `Question_Points` INT NOT NULL,
  `Question_Category` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Question`),
  UNIQUE INDEX `ID_Question_UNIQUE` (`ID_Question` ASC) VISIBLE,
  UNIQUE INDEX `Question_Text_UNIQUE` (`Question_Text` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Answers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Answers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Answers` (
  `ID_Question` INT NOT NULL,
  `ID_Answer` INT NOT NULL,
  `Answer_Text` VARCHAR(45) NOT NULL,
  `Is_Correct` TINYINT NOT NULL,
  PRIMARY KEY (`ID_Question`, `ID_Answer`),
  UNIQUE INDEX `Answer_Text_UNIQUE` (`Answer_Text` ASC) VISIBLE,
  INDEX `fk_Answers_Question_idx` (`ID_Question` ASC) VISIBLE,
  CONSTRAINT `fk_Answers_Question`
    FOREIGN KEY (`ID_Question`)
    REFERENCES `mydb`.`Question` (`ID_Question`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Quiz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Quiz` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Quiz` (
  `ID_QUIZ` INT NOT NULL,
  `Quiz_Lenght` INT NOT NULL,
  `Author` INT NOT NULL,
  PRIMARY KEY (`ID_QUIZ`),
  UNIQUE INDEX `ID_QUIZ_UNIQUE` (`ID_QUIZ` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Question_Quiz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Question_Quiz` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Question_Quiz` (
  `ID_Question` INT NOT NULL,
  `ID_QUIZ` INT NOT NULL,
  INDEX `fk_Question_Quiz_Question1_idx` (`ID_Question` ASC) VISIBLE,
  INDEX `fk_Question_Quiz_Quiz1_idx` (`ID_QUIZ` ASC) VISIBLE,
  PRIMARY KEY (`ID_Question`, `ID_QUIZ`),
  CONSTRAINT `fk_Question_Quiz_Question1`
    FOREIGN KEY (`ID_Question`)
    REFERENCES `mydb`.`Question` (`ID_Question`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Question_Quiz_Quiz1`
    FOREIGN KEY (`ID_QUIZ`)
    REFERENCES `mydb`.`Quiz` (`ID_QUIZ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Game` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Game` (
  `ID_GAME` INT NOT NULL,
  `Player_ID` VARCHAR(45) NOT NULL,
  `Score` INT NOT NULL,
  `ID_QUIZ` INT NOT NULL,
  PRIMARY KEY (`ID_GAME`),
  UNIQUE INDEX `ID_GAME_UNIQUE` (`ID_GAME` ASC) VISIBLE,
  INDEX `fk_Game_Quiz1_idx` (`ID_QUIZ` ASC) VISIBLE,
  CONSTRAINT `fk_Game_Quiz1`
    FOREIGN KEY (`ID_QUIZ`)
    REFERENCES `mydb`.`Quiz` (`ID_QUIZ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
